package predicate

const (
	ReadyContractVersion Atom = "ready.contract_version"
	ReadyRunID           Atom = "ready.run_id"
	ReadyTaskIdentity    Atom = "ready.task_identity"
	ReadyRepository      Atom = "ready.repository"
	ReadyPullRequest     Atom = "ready.pull_request"
	ReadyBaseBranch      Atom = "ready.base_branch"
	ReadyHeadBranch      Atom = "ready.head_branch"
	ReadyTaskPrefix      Atom = "ready.task_prefix"
	ReadyVerifiedHead    Atom = "ready.verified_head"
	ReadyCreatedAt       Atom = "ready.created_at"
	ReadyRunDirectory    Atom = "ready.run_directory"

	BindingTask       Atom = "binding.task"
	BindingRepository Atom = "binding.repository"
	BindingBaseBranch Atom = "binding.base_branch"
	BindingFreshness  Atom = "binding.freshness"

	PullRequestOpen                 Atom = "pull_request.open"
	PullRequestNotDraft             Atom = "pull_request.not_draft"
	PullRequestBase                 Atom = "pull_request.base"
	PullRequestHeadBranch           Atom = "pull_request.head_branch"
	PullRequestVerifiedHead         Atom = "pull_request.verified_head"
	PullRequestMerged               Atom = "pull_request.merged"
	PullRequestMergeCommit          Atom = "pull_request.merge_commit"
	PullRequestClosedUnmerged       Atom = "pull_request.closed_unmerged"
	PullRequestVerifiedHeadMismatch Atom = "pull_request.verified_head_mismatch"

	SafeguardReviewClear    Atom = "safeguard.review_clear"
	SafeguardChecksTerminal Atom = "safeguard.checks_terminal"
	SafeguardChecksAccepted Atom = "safeguard.checks_accepted"
	SafeguardRegression     Atom = "safeguard.regression"

	HealthStatus     Atom = "health.status"
	HealthApp        Atom = "health.app"
	HealthCommit     Atom = "health.commit"
	HealthTree       Atom = "health.tree"
	HealthBuild      Atom = "health.build"
	HealthDeployment Atom = "health.deployment"
	HealthContract   Atom = "health.contract"
	HealthStartedAt  Atom = "health.started_at"

	CheckoutClean      Atom = "checkout.clean"
	CheckoutBaseBranch Atom = "checkout.base_branch"
	CheckoutUpstream   Atom = "checkout.upstream"
	CheckoutHeadOnMain Atom = "checkout.head_on_main"
	CheckoutOrigin     Atom = "checkout.origin"

	ReceiptSourceOnMain   Atom = "receipt.source_on_main"
	ReceiptStatus         Atom = "receipt.status"
	ReceiptApp            Atom = "receipt.app"
	ReceiptBranch         Atom = "receipt.branch"
	ReceiptTree           Atom = "receipt.tree"
	ReceiptContract       Atom = "receipt.contract"
	ReceiptCommitFormat   Atom = "receipt.commit_format"
	ReceiptTreeFormat     Atom = "receipt.tree_format"
	ReceiptBinaryFormat   Atom = "receipt.binary_format"
	ReceiptDeploymentID   Atom = "receipt.deployment_id"
	ReceiptBuildID        Atom = "receipt.build_id"
	ReceiptRepository     Atom = "receipt.repository"
	ReceiptCheckpointTime Atom = "receipt.checkpoint_time"
	ReceiptFinishOrder    Atom = "receipt.finish_order"

	MergeContained        Atom = "completion.merge_contained"
	VerifiedHeadContained Atom = "completion.verified_head_contained"
	RemoteBranchAbsent    Atom = "completion.remote_branch_absent"
	WorktreeAbsent        Atom = "completion.worktree_absent"
	TaskComplete          Atom = "completion.task_complete"
	ChildrenComplete      Atom = "completion.children_complete"

	ExternalAuthenticationFailure Atom = "blocker.external_authentication"
	DeploymentFailed              Atom = "blocker.deployment_failed"
	RemoteBranchPresent           Atom = "blocker.remote_branch_present"
	WorktreePresent               Atom = "blocker.worktree_present"
	TaskIncomplete                Atom = "blocker.task_incomplete"
	ChildrenIncomplete            Atom = "blocker.children_incomplete"
)

const (
	ProfileSDLCDeploy   = "sdlc-deploy"
	ProfileSDLCRepoOnly = "sdlc-repo-only"
)
